# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: messagebus
# spec:
#   type: pubsub.redis
#   metadata:
#   - name: redisHost
#     value: localhost:6379
#   - name: redisPassword
#     value: ""

# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: messagebus
# spec:
#   type: pubsub.redis
#   metadata:
#   - name: redisHost
#     value: redis-master:6379
#   - name: redisPassword
#     secretKeyRef:
#       name: redis
#       key:  redis-password
# auth:
#   secretStore: kubernetes

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus  
spec:
  type: pubsub.nats
  metadata:
  - name: natsURL
    value: nats-client.default.svc.cluster.local:4222
