apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: notification
spec:
  type: bindings.twilio.sms
  metadata:
  - name: fromNumber
    value: "+12037180573"
  - name: accountSid 
    secretKeyRef:
      name: twilio
      key: account-sid
  - name: authToken
    secretKeyRef:
      name: twilio
      key: auth-token