name: Dapr Component Deploys
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_daprtalk_kubeConfig }}

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: daprtalks.azurecr.io
        container-registry-username: $${{ secrets.acr_daprtalks_username }}
        container-registry-password: ${{ secrets.acr_daprtalks_password }}
        secret-name: daprtalkdockerauth

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'default'
        secret-type: 'generic'
        arguments:  --from-literal=access-key=${{ secrets.AZURE_COSMOS_ACCESS_KEY }}
        secret-name: azure-cosmos       
        
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'default'
        secret-type: 'generic'
        arguments:  --from-literal=account-sid=${{ secrets.TWILIO_ACCOUNT_SID }} --from-literal=auth-token=${{ secrets.TWILIO_AUTH_TOKEN }}
        secret-name: twilio             
  
    - uses: azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: |
          components/messagebus.yaml
          components/statestore.yaml

    - uses: azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: |
          k8s-deploy/ingress.yaml