name: Build & Deploy Delivery Service

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: delivery-service
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy     
    steps:    
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: daprtalks.azurecr.io
        username: ${{ secrets.acr_daprtalks_username }}
        password: ${{ secrets.acr_daprtalks_password }}

    - name: Build and push Delivery Service to ACR
      id: build-delivery-service
      run: |
        docker build "$GITHUB_WORKSPACE/delivery-service" -f  "delivery-service/Dockerfile" -t daprtalks.azurecr.io/delivery-service:${{ github.sha }}
        docker push daprtalks.azurecr.io/delivery-service:${{ github.sha }}

    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_daprtalk_kubeConfig }}

    - uses: azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: |
          k8s-deploy/delivery-service.yaml
        images: |
          daprtalks.azurecr.io/delivery-service:${{ github.sha }}
        imagepullsecrets: |
          daprtalkdockerauth