name: Build & Deploy Order UI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: order-ui
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy     
    steps:    
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: daprtalks.azurecr.io
        username: ${{ secrets.acr_daprtalks_username }}
        password: ${{ secrets.acr_daprtalks_password }}

    - name: Build and push Order UI to ACR
      id: build-order-ui
      run: |
        docker build "$GITHUB_WORKSPACE/order-ui" -f  "Dockerfile" -t daprtalks.azurecr.io/order-ui:${{ github.sha }}
        docker push daprtalks.azurecr.io/order-ui:${{ github.sha }}

    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_daprtalk_kubeConfig }}

    - uses: azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: |
          order-ui/order-ui.yaml
        images: |
          daprtalks.azurecr.io/order-ui:${{ github.sha }}
        imagepullsecrets: |
          daprtalkdockerauth